language: ruby
rvm:
- 2.4 # Keep this in sync with .rubocop.yml
- 2.5
# The latest version of Ruby is tested below (we use it for our code coverage
# calculation and RuboCop run).
script: bundle exec rspec
matrix:
  include:
  - rvm: 2.6
    script:
    - bundle exec rspec
    - gem install --no-document rubocop rubocop-rspec-focused && rubocop
    env:
    - CODE_COVERAGE=true
branches:
  only:
  - master
  # We always run tests for PRs. This prevents running PR tests twice (once "for
  # the PR" and once "for the branch"), though we do want tests to run always
  # run on master.
notifications:
  email: false
  slack:
    secure: Me2JUx/uXZcHPAU2Gsm8j8ygD526JkDZtJ+MToRPdUFhNTU+wuxUkBAmAP5JHabG45wF51P10B/MW1mD+b6ZCQ37r4N8hu7HAxPLhfvUm15g1vIqDFPExqw9jCbFheedQ5oe3BfzX74MA+mxwgSZLYhvio0Tx+S8j/MtR75N6U8=
